spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB



  datasource:
    url: jdbc:mysql://124.223.185.178:3306/aaa
    username: root
    password: mysql@ch
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      aop-patterns: com.ch.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false

      web-stat-filter: # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat: # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false


  #    type: com.zaxxer.hikari.HikariDataSource

  jdbc:
    template:
      query-timeout: 3


#整合Mybatis
#mybatis:
##  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

#整合redis
  redis:
    host: 124.223.185.178
    port: 6379
    password: rreeddiiss
    client-type: jedis
  #redis://user:password@example.com:6379
#    url: redis://user:rreeddiiss@124.223.185.178:6379

  #可视化工具
  boot:
    admin:
      client:
        url: http://localhost:8081
#        instance:
#          prefer-ip: true
#  application:
#    name: boot-05-web-admin


# actuator  监控端点配置
management:
  #所有端点配置
  endpoints:
    web:
      exposure:
        #web方式暴露所有端点
        include: "*"
    #enabled-by-default: true #开启所有监控端点
    enabled-by-default: true # 默认开启全局 检测端点

  #具体端点配置
  endpoint:
    health:
      show-details: always
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true

info:
  appName: boot-admin
  version: 2.0.1
  mavenProjectName: @project.artifactId@  #使用@@可以获取maven的pom文件值
  mavenProjectVersion: @project.version@

